#!/bin/bash
#
# BASALT VIO Test Execution Script - Phase B
# Runs Visual-Inertial Odometry on EuRoC datasets and saves trajectories
#
# Usage: ./scripts/run_vio_tests.sh
#

set -e  # Exit on error

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
BASALT_VIO="/workspace/external/basalt/build/basalt_vio"
CALIB_FILE="/workspace/configs/my_euroc_calib.json"
CONFIG_FILE="/workspace/external/basalt/data/euroc_config.json"
DATA_DIR="/workspace/data"
RESULTS_DIR="/workspace/results"

# Ensure results directories exist
mkdir -p "${RESULTS_DIR}/trajectories"
mkdir -p "${RESULTS_DIR}/groundtruth"
mkdir -p "${RESULTS_DIR}/stats"
mkdir -p "${RESULTS_DIR}/marg_data"
mkdir -p "${RESULTS_DIR}/plots"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}BASALT VIO - Phase B Dataset Testing${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if BASALT VIO executable exists
if [ ! -f "${BASALT_VIO}" ]; then
    echo -e "${RED}Error: BASALT VIO executable not found at ${BASALT_VIO}${NC}"
    exit 1
fi

# Function to run VIO on a dataset
run_vio_test() {
    local SEQUENCE_NAME=$1
    local DATASET_PATH=$2
    
    echo -e "${YELLOW}----------------------------------------${NC}"
    echo -e "${YELLOW}Testing: ${SEQUENCE_NAME}${NC}"
    echo -e "${YELLOW}----------------------------------------${NC}"
    
    # Check if dataset exists
    if [ ! -d "${DATASET_PATH}/mav0" ]; then
        echo -e "${RED}Error: Dataset not found at ${DATASET_PATH}${NC}"
        return 1
    fi
    
    # Output paths
    TRAJ_OUTPUT_TUM="${RESULTS_DIR}/trajectories/traj_${SEQUENCE_NAME}.csv"
    GT_OUTPUT="${RESULTS_DIR}/groundtruth/gt_${SEQUENCE_NAME}.csv"
    STATS_OUTPUT="${RESULTS_DIR}/stats/result_${SEQUENCE_NAME}.json"
    MARG_DIR="${RESULTS_DIR}/marg_data/${SEQUENCE_NAME}"
    
    # Create marginalization directory
    mkdir -p "${MARG_DIR}"
    
    echo "Dataset: ${DATASET_PATH}"
    echo "Output:  ${TRAJ_OUTPUT_TUM}"
    echo ""
    
    # Record start time
    START_TIME=$(date +%s)
    
    # Run BASALT VIO
    echo "Running BASALT VIO..."
    "${BASALT_VIO}" \
        --dataset-path "${DATASET_PATH}" \
        --dataset-type euroc \
        --cam-calib "${CALIB_FILE}" \
        --config-path "${CONFIG_FILE}" \
        --show-gui 0 \
        --use-imu 1 \
        --marg-data "${MARG_DIR}" \
        --save-trajectory tum \
        --result-path "${STATS_OUTPUT}"
    
    # Record end time
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    
    # Move generated trajectory file from current directory
    if [ -f "trajectory.txt" ]; then
        mv trajectory.txt "${TRAJ_OUTPUT_TUM}"
        echo -e "${GREEN}✓ Trajectory saved (TUM format): ${TRAJ_OUTPUT_TUM}${NC}"
    else
        echo -e "${RED}✗ Error: Trajectory file not generated${NC}"
        return 1
    fi
    
    # Move ground truth file if generated by BASALT
    if [ -f "groundtruth.txt" ]; then
        mv groundtruth.txt "${GT_OUTPUT}"
        echo -e "${GREEN}✓ Ground truth saved: ${GT_OUTPUT}${NC}"
    fi
    
    # Move statistics files
    if [ -f "stats_vio.ubjson" ]; then
        mv stats_vio.ubjson "${RESULTS_DIR}/stats/stats_vio_${SEQUENCE_NAME}.ubjson"
        echo -e "${GREEN}✓ Statistics saved${NC}"
    fi
    if [ -f "stats_sums.ubjson" ]; then
        mv stats_sums.ubjson "${RESULTS_DIR}/stats/stats_sums_${SEQUENCE_NAME}.ubjson"
    fi
    if [ -f "stats_all.ubjson" ]; then
        mv stats_all.ubjson "${RESULTS_DIR}/stats/stats_all_${SEQUENCE_NAME}.ubjson"
    fi
    
    # Display summary
    if [ -f "${TRAJ_OUTPUT_TUM}" ]; then
        NUM_POSES=$(wc -l < "${TRAJ_OUTPUT_TUM}")
        echo -e "${GREEN}✓ Generated ${NUM_POSES} poses in ${DURATION} seconds${NC}"
    fi
    
    echo ""
    return 0
}

# Main execution
echo "Starting VIO tests..."
echo ""

# Test 1: MH_01_easy (Machine Hall - Easy)
run_vio_test "mh_01_easy" "${DATA_DIR}/MH_01_easy"

# Test 2: V1_03_difficult (Vicon Room 1 - Difficult)
run_vio_test "v1_03_difficult" "${DATA_DIR}/V1_03_difficult"

# Summary
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Phase B Testing Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Results saved in:"
echo "  Trajectories: ${RESULTS_DIR}/trajectories/"
echo "  Ground truth: ${RESULTS_DIR}/groundtruth/"
echo "  Statistics:   ${RESULTS_DIR}/stats/"
echo ""
echo "Next: Phase C - Run evaluation with evo toolkit"
echo "  Example: evo_ape euroc gt_mh_01_easy.csv traj_mh_01_easy_tum.txt --align --plot"
echo ""
